<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Application_model extends CI_Model
{

    public $table = 'application';
    public $id = 'app_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('app_id,application_id,user_id,application_date,application_evaluate_date,application_status');
        $this->datatables->from('application');
        //add this line for join
        //$this->datatables->join('table2', 'application.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('application/read/$1'),'Read')." | ".anchor(site_url('application/update/$1'),'Update')." | ".anchor(site_url('application/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'app_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('app_id', $q);
	$this->db->or_like('application_id', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('application_date', $q);
	$this->db->or_like('application_evaluate_date', $q);
	$this->db->or_like('application_status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('app_id', $q);
	$this->db->or_like('application_id', $q);
	$this->db->or_like('user_id', $q);
	$this->db->or_like('application_date', $q);
	$this->db->or_like('application_evaluate_date', $q);
	$this->db->or_like('application_status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Application_model.php */
/* Location: ./application/models/Application_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-13 08:36:14 */
/* http://harviacode.com */