<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class User_detail_model extends CI_Model
{

    public $table = 'user_detail';
    public $id = 'detail_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('detail_id,detail_fullname,detail_phone,detail_email,detail_address,user_id');
        $this->datatables->from('user_detail');
        //add this line for join
        //$this->datatables->join('table2', 'user_detail.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('user_detail/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i> View', array('class' => 'btn btn-info btn-sm'))." | ".anchor(site_url('user_detail/update/$1'),'<i class="fa fa-eye" aria-hidden="true"></i> Update', array('class' => 'btn btn-success btn-sm'))." | ".anchor(site_url('user_detail/delete/$1'),'<i class="icofont icofont-ui-delete" aria-hidden="true"></i> Delete', array('class' => 'btn btn-danger btn-sm'),'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'detail_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('detail_id', $q);
        $this->db->or_like('detail_fullname', $q);
        $this->db->or_like('detail_phone', $q);
        $this->db->or_like('detail_email', $q);
        $this->db->or_like('detail_address', $q);
        $this->db->or_like('user_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('detail_id', $q);
    	$this->db->or_like('detail_fullname', $q);
    	$this->db->or_like('detail_phone', $q);
    	$this->db->or_like('detail_email', $q);
    	$this->db->or_like('detail_address', $q);
    	$this->db->or_like('user_id', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_detail_model.php */
/* Location: ./application/models/User_detail_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-05-14 15:42:53 */
/* http://harviacode.com */